<?php

use Illuminate\Database\Seeder;
use EDS_site\Models\Symptom;

class SymptomTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Symptom::class, 20)->create();

        $symptoms = [
            ['title' => 'Micro- en macrotraumata', 'info' => '<p>Pati&euml;nten met hEDS melden allemaal gewrichtspijn (Rombaut, 2010). Gewrichtshypermobiliteit en -instabiliteit komt voor tijdens dagelijkse activiteiten (Levy, 2004) met herhaaldelijke dislocaties als gevolg. (Castori, 2010) (Rombaut, 2010). Daarnaast veroorzaakt de hyperlaxiteit bewegingen in het gewricht waarvoor het eigenlijk niet gemaakt is. Daardoor geraken gewrichtsstructuren overbelast en ontstaan traumata van ligamenten, pezen, spieren, synovium (slijmvlies) en kraakbeen van de hypermobiele gewrichten. </p>
            <p>Tot voor kort werd dan ook aangenomen dat de pijn voornamelijk door gewrichtsschade werd veroorzaakt. (Camerota, 2010). In overeenstemming daarmee halen pati&euml;nten vaak zelf aan dat hun pijn samenhangt met de herhaalde luxaties en letsels aan weke weefsels. De meest hevige pijn hangt meestal ondubbelzinnig samen met voorafgaande operatie, hypermobiliteit en dislocaties (Sacheti, 1997). Sub- en dislocaties komen spontaan of met minimale trauma voor en kunnen acuut pijnlijk zijn (Levy, 2004). Deze dislocaties resulteren in herhaaldelijke letsels van de weke delen en zo ontstaat secundair opnieuw pijn (Sacheti, 1997). Voor de meeste pati&euml;nten is een medische interventie niet nodig. Het gewricht gaat spontaan terug op zijn plaats of kan zelf op de plaats terug gezet worden. Maar de pijn kan uren tot dagen blijven (Levy, 2004). Het kan ook zijn dat de pati&euml;nt deze traumata niet meteen gewaar wordt, maar pas later herhaaldelijke en blijvende pijn ervaart. Deze pijn komt hoogstwaarschijnlijk voor uit het musculoskeletaal stelsel en de pieken van pijn zouden te maken hebben met herhaalde subsluxaties en dislocaties. (Voermans, 2010)</p>
            <p>De gewrichtsinstabiliteit resulteert waarschijnlijk in een verhoogde mechanische stress, waardoor meer degeneratieve veranderingen voorkomen (Levy, 2004) (Rombaut, 2010). Vroege degeneratie zoals ostioartritis is mogelijk, maar niet zowiezo aanwezig. Herhaaldelijke microtraumata kunnen wel ook leiden tot grotere problemen zoals bijvoorbeeld een labrumscheur van de heup. </p>
            <p>Een behandeling is er in de eerste plaats op gericht om te voorkomen dat de gewrichten voorbij het normale bewegingsbereik gaan. Met andere woorden, de bewegingen moeten binnen dezelfde grenzen gehouden worden als bij iemand die niet hypermobiel is, omdat over deze grens gaan kan leiden tot langdurige traumatische artritis. Dit kan door kinesitherapie ter versterking van de spieren en ter stabilisering van de gewrichten. Daarnaast kunnen ook bepaalde braches de nodige hulp bieden. Het oplossen van veelvuldige luxaties door een operatie dient zoveel mogelijk vermeden te worden. Soms is een operatie nodig om breuken of zelfs gewrichtsproblemen te behandelen. Aangezien de zachte weefsels opnieuw kunnen uitrekken is dit meestal geen oplossing en keren de problemen, vaak nog in grotere mate, terug. (Aresh Hashemi-Nejad, 2016)</p>'],

            ['title' => 'Chronische pijn', 'info' => '<p>Meer informatie voor behandelaars kan, na aanmelding als behandelaar, op deze website terug gevonden worden. <br />
            Waar men er normaal van uit gaat dat instabiele gewrichten verholpen kunnen worden door het trainen van de spieren, is dat bij EDS minder evident. Aangezien bindweefsel zich ook in spieren, pezen en zenuwen bevindt, zijn deze beduidend minder trainbaar. De behandeling spitst zich dan ook vooral toe op mobilisaties binnen de pijngrenzen, tonificaties in lichte mate van alle betrokken spiergroepen, bindweefselmassage en lichte oefentherapie, ergonomie en houdingscorrecties, beperkt in de mate van wat de pati&euml;nt op die dag kan uitvoeren. Doel is voornamelijk het minderen van de pijn en het stabiliseren van de algemene toestand van de pati&euml;nt, maar dit is vaak moeilijk. </p>
            <p>Om de gewrichten te beschermen en te ondersteunen, maar ook om het dagelijks functioneren gemakkelijker te maken zijn tal van hulpmiddelen beschikbaar. Dit omvat eventueel noodzakelijke braces, steunzolen of orthopedische schoenen,... maar ook hulpmiddelen zoals een rolstoel, douchezitje, elektrische fiets, aangepaste wagen,.... Verder op de website vindt u hierover meer informatie. </p>
            <p>Pijnmedicatie is een noodzakelijk element in de pijnbestrijding. Hierbij wordt deze verdeeld in drie trappen, waarbij men pas de volgende trap neemt, indien de vorige de pijn onvoldoende stilt. <br />
            Trap 1 omvat de niet-opio&iuml;de analgetica. Dit zijn pijnstillers tegen lichte pijn. Hiertoe behoren:<br />
            Paracetamol: heeft een koortswerende en pijnstillende werking. Het is de meest veilige pijnstiller, maar overdosering kan leiden tot leverproblemen. Paracetamol is vrij verkrijgbaar. <br />
            Acetylsalicylzuur: is een koortswerend en pijnstillend middel dat bij een hogere dosis ook ontstekingsremmend werkt. Het kan aanleiding geven tot maagproblemen, en werkt bloedverdunnend. Ook deze medicatie is vrij verkrijgbaar.<br />
            Niet-stero&iuml;dale antiflogistica (NSAISs) hebben een goede werking als ontstekingsremmer, maar zijn niet aangewezen als pijnstiller. Aangezien de vele mogelijke bijwerkingen wordt het product meestal maximum twee weken gebruikt. Deze medicatie is enkel op doktersvoorschrift te verkrijgen. </p>
            <p>Trap 2 omvat de zwakke opio&iuml;de analgetica. Dit zijn pijnstillers tegen milde tot ernstige pijn. Vaak is er ook meer kans op bijwerkingen, die veelal optreden bij het opstarten van de medicatie.<br />
            Code&iuml;ne in combinatie met paracetamol is vaak de eerste keuze indien paracetamol op zich onvoldoende werkt. Tramadol, dextropropoxyfeen, pentazocine en tilidine zijn andere middelen die tot deze trap behoren. Deze medicatie wordt opgestart in overleg met de behandelende arts, en is enkel te verkrijgen op voorschrift.<br />
             <br />
            Trap 3 zijn de sterke opio&iuml;de analgetica. De werking tegen pijn is hier het sterkst, maar ook het aantal bijwerkingen neemt toe. Het gaat hier om medicatie zoals morfine, buprenorfine, fentanyl, hydromorfon, methadon en oxycodon. Het innemen van deze medicatie gebeurt steeds onder begeleiding van de behandelende arts, en op voorschrift. </p>
            <p>Daarnaast zijn er nog een aantal medicamenten die geen pijnstillers zijn, maar toch een gunstige invloed hebben op de pijnstelling. Dit zijn producten die bijvoorbeeld inwerken op de geleiding van prikkels over de zenuwen, zoals bepaalde medicatie tegen epilepsie en depressie. Ook spierontspanners kunnen een positief effect hebben, ook al dient men voorzichtig om te springen met deze medicatie bij EDS. Corticostero&iuml;den werken soms ook pijnstillend. De meeste van deze medicatie hebben een belangrijk aantal bijwerkingen. Het hangt dan ook van pati&euml;nt tot pati&euml;nt af, of deze medicatie als positief of negatief ervaren wordt. Opvolging door de behandelende arts is hier zeker van groot belang.</p>
            <p>Daarnaast kan men ook bijkomende medicijnen voorgeschreven worden om de bijwerkingen van de noodzakelijk pijnmedicatie te verminderen, zoals laxeermiddelen, middelen tegen misselijkheid en braken,....</p>
            <p>Pijnmedicatie wordt altijd besproken met de behandelende arts, die de meest aangewezen persoon is om daarin te begeleiden. Ook voor het langdurig innemen van medicatie waarvoor geen voorschrift vereist is, is het advies van de arts aangewezen. </p>
            <p>Daarnaast kunnen ook bepaalde voedingsupplementen een gunstig effect hebben (Mantle, Wilkins, &amp; Preedy, 2005). Hierbij dient met gebruik te maken van een specifieke (en potentieel synergetische) combinatie van voedingssupplementen, bestaande uit calcium, carnitine, co-enzym Q(10), glucosamine, magnesium, methylsulfonyl methaan, pyknogenol, silica, vitamine C, en vitamine K, in doseringen waarvan eerder is aangetoond dat ze effectief zijn bij de bevordering van de normale weefselfunctie in andere aandoeningen.</p>'],

            ['title' => 'verstoorde proprioceptie', 'info' => '<p>Proprioceptie, (positiezin), is het vermogen om een positie van een lichaamsdeel in de ruimte te kunnen waarnemen. Met andere woorden: het is bijvoorbeeld weten hoe de stand van de voeten is, zonder te kijken. Ook het vermogen om een correcte inschatting te kunnen maken van de nodige spierkracht voor een welbepaalde handeling is hierbij inbegrepen. Indien deze functies verstoord zijn, is het vanzelfsprekend dat deze pati&euml;nten moeilijkheden ervaren in dagdagelijkse handelingen. Het niet juist kunnen afstellen van de spierkracht of het niet herkennen van de eigen lichaamspositie is beperkend. </p>
            <p>Proprioceptie werkt op basis van zenuwcellen die het brein informeren over de houding van spieren en ledematen. Deze cellen, ook proprioceptoren genoemd, bevinden zich op de overgang tussen spieren en pezen, en geven de informatie over de activiteit van de spieren door aan de hersenen. Ook in de pezen van de spier bevinden zich een type proprioceptoren. Ze meten de spanning van de spier en zorgen er voor dat de spanning niet te groot wordt, en de spier niet beschadigd wordt. </p>
            <p>Een verstoorde proprioceptie behoort tot de primaire manifestaties bij EDS. Een proprioceptief tekort kan leiden tot letsel. Daarnaast blijkt dat hoe groter de hypermobiliteit, hoe meer proprioceptieve problemen er zijn. (Holly A. Clayton, 2013) Het niet juist kunnen inschatten van de plaats van de ledematen, leidt tot het onbewust overstrekken van gewrichten. Luxaties en subluxaties, met behorend letsel, zijn hiervan het logisch gevolg. </p>
            <p>Bovendien hebben personen met een gedaalde proprioceptie en gedaalde spierkracht vaak ook co&ouml;rdinatie- en evenwichtsproblemen. Dit leidt tot loopstoornissen, een verhoogde valfrequentie en een slechter evenwichtsvertrouwen. Hieruit volgt een afname van de veiligheid van het staan in het dagelijks leven. (Rombaut L., 2011)</p>
            <p>De oorzaak van de verstoorde prioproceptie bij EDS is nog niet gekend. Een mogelijke verklaring is het optreden van beschadigingen ter hoogte van de gevoelszenuwcellen (proprioceptoren) in het gewricht als gevolg van de hypermobiliteit. Een tweede mogelijkheid is een verminderde activatie van de proprioceptoren als gevolg van de laxiteit van het gewricht. Een derde verklaring is dat een verminderde proprioceptie leidt tot het verkeerd belasten van een gewricht waardoor de gevoelszenuwcellen beschadigd kunnen worden en laxiteit in het kapsel en de ligamenten kunnen optreden. (Malik A.K., 1994)</p>
            <p>Uit onderzoek blijkt dat bij EDS-patienten de verstoorde proprioceptie voor een deel met training en visuele compensatie te verhelpen is. Meer onderzoek is nodig zijn om te bepalen waarom de gewrichtshypermobiliteit bij EDS gerelateerd is aan proprioceptieve tekorten en de omvang van de daaruit voortvloeiende klinische gevolgen. (Holly A. Clayton, 2013)</p>'],

            ['title' => 'gedaalde spierkracht', 'info' => '<p>Mild tot matig verminderde spierkracht komt voor bij alle EDS-types. De spierzwakte is duidelijk aanwezig bij spiergroepen die instaan voor het buigen van nek, romp, heup en knie en die instaan voor het strekken van de heup. Milde spierzwakte werd vastgesteld bij vijf bilaterale spiergroepen. (Voermans NC, 2009)</p>
            <p>De oorzaak en manifestatie van deze verminderde spierkracht is nog onduidelijk. Men denkt onder andere aan een gevolg van de gedaalde proprioceptie. Hierdoor zou een verminderde activatie van de spieren plaats vinden. (Malik A.K., 1994). </p>
            <p>Een andere mogelijkheid is dat de verminderde spierkracht een gevolg is van fysieke deconditionering. De verminderde maximale kracht is mogelijks te verklaren door pijngerelateerde inactiviteit, laxiteit van de ligamenten en instabiele gewrichten. (Sahin N., 2008) Met andere woorden, wanneer men door pijn minder beweegt, gaat ook de algemene toestand van de spieren achteruit. </p>
            <p>Verder wordt ook gedacht aan een spierinhibitie (verschijnsel dat door veelvuldige prikkelingen van een spier de aktie van die spier vermindert) die veroorzaakt wordt door het centrale zenuwstelsel vanwege de pijnlijke gewrichten (reflexinhibitie). </p>
            <p>Een andere hypothetische verklaring voor verminderde spierkracht bij de EDS-HT pati&euml;nten kan ook gezocht worden in een veranderde zenuwgeleiding. Een studie waarin de zenuwgeleiding bij EDS-pati&euml;nten vergeleken werd met een gezonde controlegroep toonde aan dat de zenuwgeleiding abnormaal was bij 38% van de EDS pati&euml;nten. Daarnaast werd opgemerkt dat 13% van de EDS populatie voldeed aan de criteria van een sensorimotorisch axonale polyneuropathie. <br />
            Door de verandering in de zenuwgeleiding worden de spiervezels minder geprikkeld. Hierdoor kan minder spierkracht ontwikkeld worden. (Voermans NC, 2009)</p>
            <p>Anderzijds wordt er gedacht aan een structurele oorzaak. De oorzaak van een verminderde spierfunctie kan ook gezocht worden in wijzigingen in de extracellulaire matrix van de spier en de zenuw zelf. De veranderingen in de extracellulaire matrix van de spier kan mogelijks leiden tot een disfunctie van de myofasciale krachtsoverdracht, wat mogelijks leidt tot een verminderde spierkracht. Men kan dus stellen dat het bindweefsel in de spier zodanig is aangetast dat de spier niet meer normaal kan functioneren. (Voermans NC, 2009)</p>
            <p>Ook spierkrampen zijn een vaak voorkomende klacht is bij hEDS pati&euml;nten. (Rombaut, 2010) Een mogelijke verklaring is het vermoeden dat bij deze pati&euml;nten het bindweefsel in de spierpezen vervormbaar is. De spierpezen vormen de verbinding tussen de spieren en de aanhechting aan het bot. Om te bewegen trekt de spier samen. De spier wordt korter en dikker en trekt aan de pees, die verlengd wordt. Als de spierpezen maximaal verlengd zijn, beweegt men. Maar aangezien de kracht die door de spieren ontwikkeld wordt bij hEDS grotendeels resulteert in peesvervorming en slechts tendele in het verlengen van de pees, zal de spier steeds verder moeten verkorten, om te kunnen bewegen. Daardoor kan de spier een te grote verkorting maken, waardoor mogelijks spierkrampen kunnen ontstaan. </p>
            <p>Naast verminderde spierkracht is er ook heel frequent sprake van verminderde krachtuithouding of duurkracht. (Rombaut L, 2012). Bijgevolg zijn de functionele capaciteiten van veel pati&euml;nten sterk belemmerd door een snelle spiervermoeidheid. Deze treed heel snel op en is onredelijk groot ten opzichte van de mate van spieractiviteit. Een groot aantal pati&euml;nten is niet in staat om een grote afstand te wandelen, trappen te lopen,... en kan ook geen zwaardere huishoudelijke activiteiten uitvoeren. Ook de tijd nodig om terug te recupereren is abnormaal lang. </p>
            <p>Of het mogelijk is om de spierkracht en het uithoudingsvermogen te verbeteren door passende trainingsprogrammas dient nog ge&euml;valueerd te worden in verdere studies. (Rombaut L, 2012)</p>'],

            ['title' => 'verminderde botmassa', 'info' => '<p>Er kan een verminderde botmassa zijn, veroorzaakt door verscheidene factoren zoals verminderde proprioceptie, verminderde spierkracht of verminderde fysieke activiteit. Verminderde botmassa is nefast daar het fractuurrisico groter wordt.</p>'],
            
            ['title' => 'cardiovasculaire problemen', 'info' => '<p>Bloedvaten bestaan voor een groot deel uit collageen. De fragiliteit van de bloedvaten uit zich voornamelijk door het gemakkelijk oplopen van blauwe plekken en neusbloedingen oplopen en het ervaren van licht verlengde bloedingen. (Callewaert B., 2008; Levy, 2004) Kwetsbaarheid van de haarvaten (kleinste bloedvaten) is soms merkbaar aan de voorzijde van de benen, onder de knie&euml;n (Castori, 2010). Er kunnen spontaan blauwe plekken optreden, meestal op dezelfde plaatsen. </p>
            <p>Bij het vasculaire type is er risico op een aneurysma. Een aneurysma is een plaatselijke verbreding van een slagader (aorta). De wand van de ader wordt daar zwakker en kan dan zelfs onder normale bloeddruk scheuren. Die scheur veroorzaakt een levensbedreigende bloeding. Daarnaast zijn er ook levensbedreigende met de darm en de baarmoeder, maar ook bij het hart kunnen zich complicaties voordoen. (Jiang S., 2012)</p>
            <p>Een op drie tot de helft van de personen met hEDS en klassieke type melden daarnaast atypische borstpijn, hartkloppingen in rust of tijdens inspanning en/of orthostatische intolerantie (Rowe, 1999). Hakim A. et al, vermeld dat cardiovasculaire autonome disfunctie kan aanwezig zijn onder de vorm van Orthostatische Intolerantie, Orthostatische Hypotensie, Posturaal Orthostatische Tachycardie Syndroom, of Neraal Gemedieerde Hypotensie. De incidentie, prevalentie en natuurlijke voorgeschiedenis van deze aandoeningen zijn nog steeds niet gekwantificeerd, maar waarnemingen van gespecialiseerde klinieken suggereren dat ze vaak gezien worden bij hEDS. Er is een groeiende kennis van hoe hEDS-gerelateerde fysieke en fysiologische pathologie bijdraagt aan de ontwikkeling van deze aandoeningen. (Hakim A., 2017)</p>
            <p>Structurele hartafwijkingen zijn over het algemeen mild en niet frequent (Levy, 2004). , Prolaps van de mitraalklep of triscuspidaalklep komt voor, maar afwijkingen aan de andere kleppen zijn heel zeldzaam. Verwijding van de aortawortel, wat resulteert in aortaklepinsufficientie komt wel meer dan gemiddeld voor bij EDS van het klassieke type en hEDS, en zelfs vaker dan mitralis klepverzakking. (Wenstrup RJ, 2000; McDonnell NB, 2006) <br />
            Er is tot nu toe weinig opvolging van deze pati&euml;nten. Maar gezien de normale levensverwachtingen van personen met cEDS/hEDS kan echter verwacht worden dat dit niet leidt tot ernstige cardiale of vasculaire klinische gevolgen. (Atzinger CL, 2011)</p>'],

            ['title' => 'orthostatische intolerantie', 'info' => '<p>Orthostatische intolerantie is een abnormale reactie van de bloedcirculatie op (langdurig) rechtstaan (Rowe, 1999). Kenmerken zijn een lage bloeddruk en een snel of onregelmatig hartritme. De symptomen bestaan uit een licht gevoel in het hoofd, duizeligheid, vermoeidheid, wazig zicht, vermindering van de concentratie, misselijkheid, buikpijn, hartkloppingen, kortademigheid en soms flauwvallen. Een belangrijke oorzaak is de overmatige opstapeling van bloed in de circulatie van de onderste ledematen en ingewanden, ge&iuml;nduceerd door de invloed van zwaartekracht op het lichaam. Normaal verhindert het lichaam dit door het automatisch vernauwen van de slagaders, zodat de bloedtoevoer naar de onderste ledematen beperkt wordt. (Farquhar, 2000). Bij een beschadiging of disfunctie van het autonoom zenuwstelsel kan dit mogelijks niet op de juiste manier werken. </p>
            <p>Orthostatische klachten treden voornamelijk op na rechtop komen uit een zittende of liggende positie of na langdurig rechtop staan. Eenvoudige activiteiten zoals eten, een warme douche nemen, lichamelijke inspanningen, vermoeidheid en warmte kunnen de orthostatische klachten verergeren. Dit resulteert in ernstige beperkingen in het dagelijkse leven.</p>
            <p>Tot op vandaag is de oorzaak van autonome disfunctie bij hEDS onbekend. Verschillende hypotheses kunnen hiervoor aangehaald worden. Indien geen duidelijke oorzaak aanwezig is, denkt men in de eerste plaats aan medicatie als oorzakelijke factor. De vaakst gebruikte medicatie bij hEDS zijn analgetica en antidepressiva (Rombaut, 2010). Dit zijn o.a. tricyclische antidepressiva, anti-epileptica, opiaten, etc.. Bij gebruik van dergelijke medicatie kan de autonome functie ontregelen en zo rechtstreeks orthostatische (en ook gastro-intestinale) klachten veroorzaken (Bradley, 2003). </p>
            <p>Een tweede mogelijke verklaring is dat hEDS -pati&euml;nten beduidend minder fysiek actief zijn dan gezonde mensen (Rombaut, 2010). Een daling van de fysieke activiteit leidt tot deconditionering. Mogelijke gevolgen zijn een verlaagd bloedvolume (hypovolemische status) en een overmatige heftige reactie van de adrenoreceptoren (Gazit, 2003; Hakim, 2004), waardoor het sympathisch zenuwstelsel gestimuleerd wordt. Dit kan vervolgens aanleiding geven tot orthostatische intolerantie. Deconditionering gaat ook gepaard met een daling van de hartslagvariabiliteit, waardoor het bloed onregelmatig stroomt naar de organen, en een toename van de hartfrequentie (Newton, 2007)</p>
            <p>Andere mogelijke verklaringen zijn een verzwakte vasculaire weefselelasticiteit zijn bij hEDS-pati&euml;nten, waardoor de aders makkelijker uitzetten en moeizamer vernauwen, of een verminderde perifere vasoregulatie als gevolg van adrenoceptor of neuronale afwijkingen. (Hakim, 2004)<br />
            </p>'],
            
            ['title' => 'orthostatische tachycardie', 'info' => '<p>Posturale orthostatische tachycardie syndroom, ook wel afgekort als POTS, is een aandoening die maakt dat de hartslag erg kan toenemen wanneer iemand vanuit een zittende of liggende positie opstaat. Men spreekt over POTS wanneer de hartslagfrequentie stijgt met minstens 30 slagen per minuur, of wanneer de hartfrequentie 120 slagen per minuut bedraagt in de eerste tien minuten na het rechtstaan. (Freeman, 2011). Daarnaast dient er ook sprake te zijn van een aantal klachten zoals, duizeligheid, zich licht in het hoofd voelen, wazig zien, moeite hebben met nadenken, beginnen transpireren, zich slap voelen en flauwvallen. Andere aandoeningen waarmee POTS geassocieerd wordt zijn slaapproblemen, chronische migraine-achtige hoofdpijn, chronische vermoeidheid, prikkelbaredarmsyndroom,.... De aandoening is onder controle te houden met een aanpassing van de levensstijl. Daarnaast is er medicatie beschikbaar die de symptomen kan bestrijden. </p>
            <p>Een eerste mogelijke verklaring voor het optreden van POTS bij hEDS is het vermoeden dat extreme veneuze pooling (het opstapelen van bloed in de aders) een belangrijke rol speelt bij POTS en orthostatische hypotensie (plotse bloeddrukdaling bij het rechtstaan). (Rowe, 1999) Het is immers aannemelijk dat aders met erg elastisch bindweefsel in grote mate gaan uitzetten, waardoor pooling ontstaat. Dit wordt aangetoond doordat de meerderheid van de pati&euml;nten een grote daling van de bloeddruk vertoont, ondanks een zeer grote hartfrequentiestijging. De bloeddrukdaling is vermoedelijk het gevolg van onvoldoende vernauwen van de aders. De grote hartfrequentiestijging is dan een poging om het falen van het perifere systeem, dat de aders doet vernauwen, te compenseren.</p>
            <p>Een andere mogelijke verklaring is een positionele compressie van de cervicale wervelzuil (PC3). (Holman, 2008) Instabiliteit van de wervelzuil kan compressie van de bloedvaten en de autonome zenuwbanen in de hand werken, wat kan zorgen voor een verstoring van de autonome functie. (Chen, 1988) Compressie kan ook optreden bij Chiari I malformatie (hierbij is een deel van de kleine hersenen uit de schedel gezakt. Vaak is er bij dit type sprake van scoliose of kyfose) (Bradley &amp;. A., 1999)<br />
            Uit onderzoek bij pati&euml;nten met fibromyalgie en prikkelbare darm syndroom bleek dat deze pati&euml;nten een verhoogde somatische pijngevoeligheid hebben. De cardiale autonome respons op pijn zou bij deze pati&euml;nten op een andere manier gebeuren, met als gevolg dat ze zich gedurende lange tijd in een staat van sympathische overactiviteit bevinden. (Chalaye, 2012). Deze disautonomie wordt gekarakteriseerd door een sympatisch zenuwstelsel dat constant overactief is, maar bij stress te weinig reactief. (Martinez-Lavin, 2007)</p>
            <p>Aangezien de ernstige invloed op vermoeidheid en levenskwaliteit is het belangrijk om de mogelijke oorzaken van POTS verder te onderzoeken. <br />
            </p>'],

            ['title' => 'gastro-intestinale klachten', 'info' => '<p>Functionele darmaandoeningen komen frequent voor bij tot hEDS (Castori, 2010; Levy, 2004). Er is sprake van chronische gastro-intestinaal discomfort, zoals brandend maagzuur, kenmerken van het prikkelbaredarmsyndroom, onverklaarbare abdominale pijn en constipatie/diarree (Castori, 2010) Problemen kunnen zich voordoen over het hele spijsverteringsstelsel: mond, slokdarm, maag, dunne darm, appendix, dikke darm, anus. (Jansen, 2005) De oorzaak kan zowel bij het zwakke bindweefsel liggen, als gerelateerd zijn aan autonome disfuncties. </p>
            <p>Fragiliteit vormt een probleem in verschillende organen. Dit kan resulteren in problemen zoals liesbreuken, navelbreuk of andere hernia&rsquo;s, verzakking van de endeldarm tijdens de vroege kindertijd en loslaten van hechtingen (Callewaert B., 2008)</p>
            <p>Tijdens een zwangerschap doen zich vaker problemen voor zoals bijvoorbeeld het spontaan scheuren van de darmen, ingewanden of baarmoeder, bekkeninstabiliteit, vroegtijdig openen van de baarmoederhals, bloedingen en complexe perineale scheuren (Callewaert B., 2008; Lind, 2002). Mits een degelijke verloskundige begeleiding, vormt zwangerschap geen probleem. De uitzondering is het vasculaire type waarbij ook meer ernstige complicaties kunnen optreden. </p>
            <p>Voornamelijk bij het klassiek en hypermobiel type wordt een associatie gezien met functionele maagproblemen zoals reflux, gastroparese, prikkelbare darm syndroom, diarree en/of obstipatie (Levy e. a., 1999).</p>
            <p>Medicatie kan de oorzaak zijn van het ontregelen van de autonome functie en zo rechtstreeks gastro-intestinale klachten veroorzaken. (Bradley J. &amp;., 2003) De vaakst gebruikte medicatie bij hEDS zijn analgetica en antidepressiva (Rombaut, 2010). Dit zijn o.a. tricyclische antidepressiva, anti-epileptica, opiaten, etc.. Veel voorkomende klachten die rechtstreeks verband houden met medicatie zijn misselijkheid, braken, obstipatie,...</p>
            <p>Autonome disfunctie leidt tot vermoeidheid. Er is ook een verband tussen gastroparese (vertraagde maagleging) en vermoeidheid. (Cohen, 2000) Daarnaast is er ook een duidelijk link tussen klachten door gastroparese en de levenskwaliteit.
            </p>'],

            ['title' => 'blaas- en bekkenbodemdysfunctie', 'info' => '<p>Er is geen duidelijk antwoord op de vraag of er een verhoogd risico is op blaasaandoeningen bij het hypermobiliteitssyndroom. Sommige studies tonen een bescheiden verhoogd risico en andere dat er niet meer risico is dan bij de algemene bevolking. (Hakim A. , 2013) </p>
            <p>Misschien belangrijker dan risico is het mechanisme waardoor deze aandoeningen ontstaan. De oorzaken van urinewegstoornissen bij het hypermobiliteitssyndroom kunnen te maken hebben met veranderingen in de anatomie van blaas en bekken, of kunnen neurologisch zijn en betrekking hebben op de sympathische controle van de blaas, of psychogeen (be&iuml;nvloed door bijvoorbeeld angst en pijn), of als gevolg van infectie en ontsteking van de urinewegen. Het is ook belangrijk om de aanwezigheid van darmproblemen te bekijken. Chronische constipatie kan de blaasfunctie be&iuml;nvloeden. (Hakim A. , 2013)</p>
            <p>Er is tot nu toe weinig onderzoek gevoerd naar de relatie tussen urologische problemen en EDS. Kinderartsen beschreven wel een relatie tussen hypermobiliteit en het functioneren van de bekkenbodem bij jonge kinderen. (McIntosc, 1996) Hierbij gaat het over klachten zoals het matig functioneren van de bekkenbodem en niet-neurogene dysfunctie van de blaassluitspier (Kort I.M. de, 2003). Symptomen daarvan waren urine-incontinentie, frequente urinewegeninfecties, obstipatie en fecale solling (remsporen). De oorzaak zou onvoldoende ondersteunend bindweefsel in de bekkenbodem door abnormale samenstelling van collageen zijn. Het is dus heel waarschijnlijk dat gelijkaardige problemen ook aanwezig zijn bij volwassen pati&euml;nten met hEDS.</p>
            <p>Een ander gekend probleem bij EDS is de aanwezigheid van een (aangeboren) blaasdivertikel. (Lock, 2005) Het is aannemelijk dat de oorzaak ligt bij de elasticiteit van de blaaswand. Een gevolg van de aanwezigheid van een blaasdivertikel is vaak een slechte lediging van de blaas. Vooral bij meisjes en vrouwen ontstaan er hierdoor urineweginfecties. Afhankelijk van de plaats van het divertikel kan een dysernegie van de blaassluitspier of reflux van de urine ontstaan. Dysernegie van de blaassluitspier leidt tot een stoornis bij het urineren. Bij reflux stroomt er urine terug naar de nier. Aangezien dit schadelijk is voor de nier, wordt in dit geval steeds ingegrepen en het divertikel operatief verwijderd.</p>
            <p>Ook het niet functioneren van de blaasspier is mogelijk bij EDS. (Lock, 2005) Men beschrijft de situatie van een jonge vrouw, waarbij geen normale samentrekkingen van de blaas plaatsvinden. Daarnaast was er wel een hoge afsluitdruk van blaashals en urinebuis. Hogere urinewegen zijn normaal en er is geen stuwing. Ook is er geen sprake van urinewegeninfecties. In dit geval was de oplossing zelfsondage, enkele malen per dag. Op die manier kon de vrouw sociaal goed functioneren en was er nauwelijks urineverlies.</p>
            <p>Voor wat betreft de hogere urinewegen worden cysteuze afwijkingen van de nier, verschillend van klassieke niercysten gemeld. (Mauseth R., 1977). Daarnaast is er een beperkt aantal beschrijvingen van een abnormale werking van de ureter (buis die loopt tussen het nierbekken en de urineblaas) waardoor de ureter en het nierbekken uitzetten. Dit kan ook ontstaan door reflux, als gevolg van een divertikel bij de blaasuitgang. (Lock, 2005)</p>
            <p>Wat vooral belangrijk is bij de behandeling van klachten van de urinewegen, is dat de behandelend arts op de hoogte is van EDS. Men dient terughoudend te zijn voor operaties, aangezien de slecht kwaliteit van huid en bindweefsel bij heel wat pati&euml;nten met EDS. (Lock, 2005). </p>
            <p>Bij de aanwezigheid van nierstenen dient men niersteenvergruizing te vermijden bij pati&euml;nten met vEDS, aangezien door die behandeling ernstige complicaties (zware bloedingen) kunnen optreden. (Eecken H van der, 2002)</p>'],

            ['title' => 'vermoeidheid', 'info' => '<p>Vermoeidheid is bij personen met EDS &eacute;&eacute;n van de meest voorkomende klachten, en heeft grote gevolgen voor het dagelijkse leven. De kans op lichamelijke vermoeidheid lijkt 5 keer zo groot, en de vermindering van activiteiten komt drie keer zo veel voor als bij de doorsnee bevolking. (R. Geenen, 2005). Hoewel dit niet vermeld staat in de diagnose criteria voor hEDS, tonen verschillende studies aan dat vermoeidheid een opvallende klacht is. (Castori, 2010) (Voermans, 2010) (Rombaut L., 2011) Men stelde vast dat 82% van de onderzochte personen met hEDS of HSD voldoen aan de criteria voor het Chronisch Vermoeidheidssyndroom (CVS). (Castori, 2011)</p>
            <p>Aangezien ernstige vermoeidheid aan de basis ligt van ernstige beperkingen, is het belangrijk dat deze opgenomen wordt in de behandeling van hEDS. Daartoe is het noodzakelijk om de mogelijke oorzaken van de vermoeidheid te achterhalen. </p>
            <p>Verschillende mogelijke oorzaken voor de vermoeidheid worden genoemd: </p>
            <p>Pijn wordt genoemd als een belangrijke voorspeller van vermoeidheid, maar alhoewel men er van uit gaat dat pijn vermoeidheid veroorzaakt, is het onderliggende mechanisme niet gekend. (Voermans, 2010) Een mogelijke hypothese is vermoeidheid omwille van slaapproblemen door de pijn. (Voermans, 2010) (Rombaut L., 2011) Pijn kan ook een gevoel van vermoeidheid veroorzaken. Veel pati&euml;nten ervaren meerdere uren per dag pijn, en men geeft aan dat men na een dag met hevige pijn moet uitrusten. (Voermans, 2010)</p>
            <p>De grotere vermoeidheid bij de hEDS pati&euml;nten kan hypothetisch ook verklaard worden door fysieke inactiviteit. Onvoldoende lichaamsbeweging wordt bij CVS en POTS als medeverantwoordelijk beschouwd voor vermoeidheid, omdat het hart- en vaatziekten veroorzaakt. (Inge De Wandele, 2016)</p>
            <p>Tevens kan hypermobiliteit een mogelijke oorzaak zijn van vermoeidheid. Spieren dienen immers harder te werken om de verzwakte functie van de ligamenten en kapsels op te vangen. (Hagen, 1996)</p>
            <p>Andere factoren die een invloed kunnen hebben op de vermoeidheid pijnmedicatie met mogelijks sedatieve bijwerkingen, een voorgeschiedenis van chirurgische ingrepen en/of co-morbiditeiten. (Voermans, 2010).</p>
            <p>Als laatste kan autonome dysfunctie bijdragen tot het gevoel van vermoeidheid. Een studie toonde aan dat orthostatische tolerantie voorkomt bij 74,4% van de pati&euml;nten met hEDS. Recht staan kan bij hEDS een aanzienlijke moeheid veroorzaken, aangezien dit leidt tot een hogere hartfrequentie dan normaal en een lagere perifere vaatvernauwing. Deze afwijkingen zijn gerelateerd aan vermoeidheid. (Inge De Wandele, 2016)<br />
            </p>'],
            
            
        ];

        Symptom::insert($symptoms);
    }
}
